# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=256)),
                ('current_frame', models.IntegerField(default=1)),
                ('first_roll', models.IntegerField(null=True)),
                ('second_roll', models.IntegerField(null=True)),
                ('strike_frame', models.IntegerField(null=True)),
                ('strike_reserve', models.IntegerField(default=0)),
                ('spare_frame', models.IntegerField(null=True)),
                ('spare_reserve', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('all_time_score', models.IntegerField(default=0)),
                ('games_bowled', models.IntegerField(default=0)),
            ],
        ),
    ]
